### ISSUE TITLE
Hardware wiring of TX/RX with the TR on the dashboard

### ISSUE THREAD

**Issue by camp0s** [ands/EsaBusModule#4]
Hi,

how did you interface the 2-wire UART of Arduino (Atmel) with the single wire bus of the device (going to TR on the dash)board?

Tnx.

**Comment by ands** [comment]
Hi camp0s,

The schematic pdf is in the repo :)
https://github.com/ands/EsaBusModule/blob/master/hardware/EsaBusModule1.0/EsaBusModule1.0_Schematic.pdf

Have fun!
ands

**Comment by camp0s** [comment]
You are right, sorry - somehow I just saw the .JPG listed..
