### ISSUE TITLE
Name of connectors

### ISSUE THREAD

**Issue by Metaln00b** [ands/EsaBusModule#5]
Hello and thank you for sharing your work.

Can you tell us what is the exact name of the used connectors?

**Comment by ands** [comment]
Hey @Metaln00b,

you'll find them if you look for HY-4* by BOOMELE, e.g. on LCSC:

https://www.lcsc.com/product-detail/_BOOMELE-Boom-Precision-Elec-_C146068.html
https://www.lcsc.com/product-detail/_BOOMELE-Boom-Precision-Elec-_C146075.html
https://www.lcsc.com/product-detail/_BOOMELE-Boom-Precision-Elec-_C146077.html

Hope that helps.

**Comment by Metaln00b** [comment]
That's awesome. Thank you 🙏
